// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qckzbhsmliszfrcssmop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFja3piaHNtbGlzemZyY3NzbW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMTk0MzQsImV4cCI6MjA1NjU5NTQzNH0.7fjvspLz0oQienf3A6MMKUC5XUIVt8MZ5R0RizHdbz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);